# Generated by Django 2.2.4 on 2022-06-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_project_App', '0002_auto_20220629_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='level',
        ),
    ]
