# Generated by Django 2.2.4 on 2022-06-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_project_App', '0004_auto_20220629_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_by',
        ),
    ]
